# coding: utf-8

"""
    Task Management API

    API for managing tasks

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_tasks_get(self) -> None:
        """Test case for tasks_get

        Get all tasks
        """
        pass

    def test_tasks_post(self) -> None:
        """Test case for tasks_post

        Create a new task
        """
        pass

    def test_tasks_task_id_delete(self) -> None:
        """Test case for tasks_task_id_delete

        Delete a task by ID
        """
        pass

    def test_tasks_task_id_get(self) -> None:
        """Test case for tasks_task_id_get

        Get a task by ID
        """
        pass


if __name__ == '__main__':
    unittest.main()
